language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build --base-href /Pixels/
  - cd dist/Pixels
  - cp index.html 404.html

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/Pixels
  on:
    branch: master